development:
  adapter: postgresql
  database: ntdb
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost

production:
  adapter: postgresql
  database: ntdb_production
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
test:
  adapter: sqlite3
  database: <%= File.join(File.expand_path("..", __dir__), "db/test.sqlite3") %>
